resolver: lts-3.16
packages:
  - location:
      git: https://github.com/eryx67/api-builder.git
      commit: 4c4c75054d0f0978dcd2d594f2dae4470466e680
  - '.'

extra-deps:
  - attoparsec-0.13.0.1
  - aeson-0.9.0.1
  - aeson-casing-0.1.0.2
  - data-default-generics-0.3
  - uri-0.1.6.3